### ISSUE TITLE
Change "married with" to "married to"

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#998] opened 2020-10-01 12:04 UTC
In the Personal Names authorities, in the editing mode, the "Type of relationship" in 500$i is, correctly, "married to" 
![image](https://user-images.githubusercontent.com/18663291/94806739-c5c42d00-03ee-11eb-916e-54528b306850.png)

but the display is still the incorrect phrase "married with":
![image](https://user-images.githubusercontent.com/18663291/94806850-f310db00-03ee-11eb-91ee-219825cc472b.png)

Can the display also be changed to "married to"?

**Comment by HirschSt** [comment] 2020-10-01 12:19
this is coded in the data itself, see eg. https://muscat.rism.info/admin/people/76321.xml and can only be resolved by maintenance script

**Comment by ahankinson** [comment] 2020-10-01 13:06
If it's only a few records you could just change it to 'married to' and then re-save the record, couldn't you?

**Comment by xhero** [comment] 2020-10-01 14:15
One sec, the problem is if you change it from the incorrect value "married with" to "married to" in the editor? I tried in 76321 and in the view I see "married to"

**Comment by ahankinson** [comment] 2020-10-01 14:17
Looks like somebody already updated it?

**Comment by xhero** [comment] 2020-10-01 14:22
me 😇 I wanted to see if the value would update in the view page, and it did.

**Comment by jenniferward** [comment] 2020-10-02 10:33
Can it please be changed to "married to" with a script? I'm finding 167 instances of "married to" and 2,113 of "married with" (in the published OPAC data). 

It's causing problems in the OPAC: "married with" displays correctly as "Spouse of"
https://opac.rism.info/search?id=pe40200689&View=rism
but "married to" doesn't display anything:
https://opac.rism.info/search?id=pe50043235&View=rism
After it's changed, I'll notify the BSB so the display is correct.

**Comment by HirschSt** [comment] 2020-10-05 07:38
As previously said, will be done by maintenance script, see https://github.com/rism-international/tasks/issues/878

**Comment by xhero** [comment] 2020-10-05 07:41
Regarding this, does it change correctly between edit and view? This is a different issue than the script if it does not work. I tested it on 1 record and the value was correctly updated.

> In the Personal Names authorities, in the editing mode, the "Type of relationship" in 500$i is, correctly, "married to"
> ![image](https://user-images.githubusercontent.com/18663291/94806739-c5c42d00-03ee-11eb-916e-54528b306850.png)
> 
> but the display is still the incorrect phrase "married with":
> ![image](https://user-images.githubusercontent.com/18663291/94806850-f310db00-03ee-11eb-91ee-219825cc472b.png)
> 
> Can the display also be changed to "married to"?

**Comment by HirschSt** [comment] 2020-10-05 07:52
Yes, if the correct value is selected, the view works as expected:

![image](https://user-images.githubusercontent.com/6461776/95053254-75034b80-06f0-11eb-863e-707d30d61571.png)

see https://muscat.rism.info/admin/people/102135.xml

**Comment by xhero** [comment] 2020-10-20 12:31
This was done in the last run of maintenance right? Can I close this?

**Comment by HirschSt** [comment] 2020-10-20 13:29
No, it's just in preparation

**Comment by HirschSt** [comment] 2020-11-10 08:49
done with https://github.com/rism-international/muscat-maintenance/blob/master/archive/20201016-remove_married.rb

**Closed by HirschSt** 2020-11-10 08:49 UTC
