### ISSUE TITLE
Checkbox "Dubious" (100$j) not working

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#130] opened 2015-04-20 17:05 UTC
I can tick it, but as soon as I save the entry it disappears. For example in title: 410000982

**Comment by lpugin** [comment] 2015-04-22 13:14
Apparently it is (sometimes?) checked by default. See http://admin.rism-ch.org/sources/406003247

**Comment by xhero** [comment] 2015-04-22 13:28
But this is correct, the marc has the Attributed to tag:
=100  1#$0143618$jAttributed to$aVranický, Pavel$d1756-1808

so the problem is that is was not checked but after saving is becomes checked?

**Comment by xhero** [comment] 2015-04-22 13:31
Indeed it does. I cannot figure out why it does not do it in testing.

**Comment by lpugin** [comment] 2015-04-22 14:25
Which means we need a quick fix. And an new release...

**Comment by xhero** [comment] 2015-04-22 14:38
Did this thing ever work? I can see what I can do

**Comment by lpugin** [comment] 2015-04-22 14:41
Yes, I think it did

**Comment by lpugin** [comment] 2015-08-24 09:21
@xhero : we need to double check this

**Comment by xhero** [comment] 2015-09-23 12:07
It creates a "$jAttributed to" and it seems to remain checked on reload. There is a fix for this in marc_json. I think we can close

**Closed** 2015-09-23 12:08 UTC
Labels: Bug, Marc editor
