### ISSUE TITLE
Display additional title information of individual entries in collection 774

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#482] opened 2017-02-15 08:46 UTC
By JW:

Dear developers,
I have an item for the Muscat wish list. In the edit mode for collections, please display title information about the individual entries. Currently only the RISM number is displayed:

![image](https://cloud.githubusercontent.com/assets/6461776/22966631/51a4d25c-f363-11e6-9dcf-8a8079d443cc.png)

In the full record view, brief title information is displayed:
![image](https://cloud.githubusercontent.com/assets/6461776/22966639/5d0ad6e6-f363-11e6-890c-94c503de47f5.png)

I need to arrange all the pieces in a different order, which is very difficult when only the number is displayed.

**Comment by xhero** [comment] 2018-06-12 09:09
Duplicate of #498

**Closed by xhero** 2018-06-12 09:09 UTC
Labels: Enhancement
